### ISSUE TITLE
Test checklist

### ISSUE THREAD

**Issue by falconx** [neontribe/spool#421]
Ideally we should test on multiple iPad devices. Note it will not run on the office iPad 2 due to the - very - old iOS version.

#### Auth
- [ ] Ensure you can login via Google
- [ ] Ensure you can login via Twitter
- [ ] Ensure you can logout

#### Layout
- [ ] Ensure Gallery (home page) layout looks correct with 1, 2, 3, 4, and 5 entries
- [ ] Ensure pages layouts are not broken in portrait orientation and that the entire UI is locked to landscape orientation
- [ ] Ensure adding max text to a Text entry does not cause layout issues with Entry previews (on home page) or individual entry pages
- [ ] Ensure adding max description text to a Picture entry does not cause layout issues with Entry teasers (on home page) or individual entry pages
- [ ] Ensure adding max description text to a Video entry does not cause layout issues with Entry teasers (on home page) or individual entry pages

#### Entry creation
- [ ] Create entry with happy sentiment
- [ ] Create entry with sad sentiment
- [ ] Create entry with single topic selection
- [ ] Create entry with multiple topic selection
- [ ] Create text entry
- [ ] Create video entry
- [ ] Create video entry with description
- [ ] Create picture entry
- [ ] Create picture entry with description

#### Functionality
- [ ] Ensure settings can be updated (access "Settings" from the hamburger menu)
- [ ] Ensure entries can be filtered from the Gallery view (home page)
- [ ] Ensure entries can be filtered from the Timeline view
- [ ] Ensure entries can be deleted (hit "Delete" from the hamburger menu on an individual entry page)
- [ ] Ensure that pressing multiple times on buttons does not cause unexpected behaviour
- [ ] Ensure Gallery (home page) carousels exist and work as expected — carousels start to appear after 5 entries have been created. There should be a max of 3 entries per carousel.
- [ ] Ensure entry created date is correct on Entry teasers (on home page) and individual entry pages
- [ ] Ensure entry sentiment icons are correct on Entry teasers (on home page) and individual entry pages
- [ ] Ensure entry topic icons are correct on Entry teasers (on home page) and individual entry pages
- [ ] Ensure view count is incremented on individual entry pages (when setting is turned on)
- [ ] Ensure view count is hidden on individual pages and is not incremented (when setting is turned off)
